### ISSUE TITLE
Official Tech Empower Bench with misconfigured mofuw

### ISSUE THREAD

**Issue by mratsim** [2vg/mofuw#44] opened 2018-06-07 05:13 UTC
The new Tech Empower bench is out includes mofuw but perf is abysmal.

I wonder if they forgot to compile with release. https://www.techempower.com/benchmarks/#section=data-r16&hw=ph&test=plaintext

**Comment by 2vg** [comment] 2018-06-07 05:40
ya, i identified the cause for this.
First of all, techempower's plaintext test uses a pipeline.

When mofuw receives a request in the posix environment, it receives it until EAGAIN or EWOULDBLOCK occurs instead of judging by linefeed.

So the request continues to flow to the same file descriptor and as a result the response to one connection does not end in perpetuity and mofuw calculates the maximum size of the response and returns an error.

However, this practice should be correct in many cases.
Is there something to make an application currently using a pipeline ...?
I do not see it at all, so I do not know whether to cure it.

**Comment by mratsim** [comment] 2018-06-07 09:42
It's probably better to as in Nim forum, I don't know anything at all about that :/

**Comment by 2vg** [comment] 2018-06-16 13:54
Yay, You can close this Issue.

I fixed the mofuw HTTP pipeline problem, so I can join the plaintext benchmark.

In the latest result I saw, there seems to be a mistake, but I know the reason.

If an error occurs, the progress of the benchmark stops there, but even if an error occurs, the result is very good, it already exceeds servlet and japronto.(servlet is 31st and japront is 29th.)

In other words, mofuw will leave the name in the topclass of framework ꒰ᐡ - ﻌ - ᐡ꒱ ♡

Cheers to mofuw and Nim, and all Nimmist 🎉

**Closed** 2018-06-16 14:34 UTC
